#ifndef FM9_ERRORS_H_
#define FM9_ERRORS_H_


//FM9 General Errors:

#define INSUFFICIENT_SPACE -1
#define INVALID_LINE_NUMBER	-2
#define NO_FRAMES_AVAILABLE	-3
#define INSUFFICIENT_FRAMES_AVAILABLE -4
#define INVALID_FRAME_NUMBER -5

#endif /* FM9_ERRORS_H_ */
